"""
test_company_onboarding_validation.py
-------------------------------------
Comprehensive validation tests for Company Onboarding form.
Tests field-level validation, bug discovery, and edge cases.

18 test cases across 10 test methods (~3-4 min runtime).
Results stored in validation_results_store.py.
Report generated by validation_report_generator.py.
"""

import os
import time
import glob
from datetime import datetime
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pytest

from common.logger import log
from pages.company_onboarding.Company_Onboarding.company_onboarding_page import CompanyOnboardingPage
from pages.company_onboarding.test.validation_results_store import validation_results

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SCREENSHOT_DIR = os.path.join(PROJECT_ROOT, "pages", "company_onboarding", "screenshots")
REPORT_DIR = os.path.join(PROJECT_ROOT, "pages", "company_onboarding", "reports")
DOWNLOAD_DIR = os.path.join(PROJECT_ROOT, "downloads")


class TestCompanyOnboardingValidation:

    # ================================================================
    # HELPERS
    # ================================================================

    def _page(self, driver):
        return CompanyOnboardingPage(driver)

    def _unique_name(self):
        return f"TestValCo_{datetime.now().strftime('%H%M%S')}"

    def _take_screenshot(self, driver, name):
        os.makedirs(SCREENSHOT_DIR, exist_ok=True)
        path = os.path.join(
            SCREENSHOT_DIR, f"{name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        )
        driver.save_screenshot(path)
        log.info(f"Screenshot: {path}")
        return path

    def _record(self, **kwargs):
        validation_results.append({
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            **kwargs,
        })

    def _open_fresh_form(self, page):
        page.navigate_to_page()
        page.wait_seconds(2)
        page.open_add_form()
        page.wait_seconds(2)

    def _fill_all_valid(self, page, company_name):
        """Fill header + Step 1 fields with valid data."""
        page.type_text(page.COMPANY_NAME_INPUT, company_name, clear_first=True)
        try:
            page._select_random_from_dropdown(page.ENTITY_GROUP_SELECT, "Entity Group")
        except Exception:
            log.warning("Could not select Entity Group")
        page.wait_seconds(0.3)

        page.type_text(page.COMPANY_SHORT_NAME_INPUT, "TestShort", clear_first=True)
        page.type_text(page.CONTACT_NAME_INPUT, "Test Contact", clear_first=True)
        page.type_text(page.COMPANY_BACKGROUND_INPUT, "Test background info for validation", clear_first=True)
        page.type_text(page.EMAIL_INPUT, "test@validation.com", clear_first=True)
        page.type_text(page.MOBILE_NUMBER_INPUT, "9876543210", clear_first=True)
        page.type_text(page.PAN_INPUT, "ABCDE1234F", clear_first=True)
        page.type_text(page.GSTIN_INPUT, "27ABCDE1234F1Z5", clear_first=True)
        page.type_text(page.CIN_INPUT, "U12345MH2020PTC123456", clear_first=True)
        page.type_text(page.PASSWORD_INPUT, "TestPass123", clear_first=True)
        try:
            page._select_random_from_dropdown(page.PLAN_TYPE_SELECT, "Plan Type")
        except Exception:
            log.warning("Could not select Plan Type")
        page._force_close_panels()

    def _navigate_to_step(self, page, step, company_name):
        """Open form and navigate to the given step (1-5)."""
        self._open_fresh_form(page)
        if step >= 1:
            self._fill_all_valid(page, company_name)
            page.go_to_step2()
            page.wait_seconds(1)
        if step >= 3:
            page.fill_promoters({"name": "Mr Test Promoter", "remark": "Test remark"}, row_index=1)
            page._click_next()
            page.wait_seconds(1)
        if step >= 4:
            page.fill_address_details({}, row_index=1)
            page._click_next()
            page.wait_seconds(1)
        if step >= 5:
            biz = {
                "business_model": "B2B",
                "market_linkages": "Direct Sales",
                "line_of_business": "IT Services",
                "additional_business_activities": "Consulting",
            }
            page.fill_business_details(biz, row_index=1)
            page._click_next()
            page.wait_seconds(1)

    def _check_field_state(self, driver, field_name):
        """
        Check Angular validation state of an input/textarea field.
        Returns: {is_invalid, is_touched, is_showing_error, error_text}
        """
        try:
            input_el = driver.find_element(
                By.CSS_SELECTOR,
                f"input[name='{field_name}'], textarea[name='{field_name}']",
            )
            classes = input_el.get_attribute("class") or ""

            error_text = ""
            try:
                form_field = input_el.find_element(
                    By.XPATH, "./ancestor::mat-form-field"
                )
                mat_errors = form_field.find_elements(By.CSS_SELECTOR, "mat-error")
                visible = [e for e in mat_errors if e.is_displayed()]
                if visible:
                    error_text = " | ".join(e.text for e in visible if e.text.strip())
            except Exception:
                pass

            return {
                "is_invalid": "ng-invalid" in classes,
                "is_touched": "ng-touched" in classes,
                "is_dirty": "ng-dirty" in classes,
                "is_showing_error": bool(error_text),
                "error_text": error_text,
            }
        except Exception as e:
            return {"error": str(e)}

    def _check_sweetalert(self, driver, timeout=5):
        """Check if SweetAlert popup is visible."""
        try:
            title_el = WebDriverWait(driver, timeout).until(
                EC.visibility_of_element_located((By.CSS_SELECTOR, "#swal2-title"))
            )
            msg = driver.find_element(By.CSS_SELECTOR, "#swal2-html-container").text
            has_btn = driver.find_elements(By.CSS_SELECTOR, ".swal2-confirm")
            return {
                "appeared": True,
                "title": title_el.text,
                "message": msg,
                "has_download_button": len(has_btn) > 0,
            }
        except Exception:
            return {"appeared": False}

    def _dismiss_sweetalert(self, driver):
        try:
            cancel = driver.find_element(By.CSS_SELECTOR, ".swal2-cancel")
            cancel.click()
            time.sleep(1)
        except Exception:
            pass

    def _download_validation_errors(self, driver):
        """Click Download Errors on SweetAlert, return saved file path."""
        try:
            before = glob.glob(os.path.join(DOWNLOAD_DIR, "*.xlsx"))
            btn = driver.find_element(By.CSS_SELECTOR, ".swal2-confirm")
            btn.click()
            time.sleep(3)
            after = glob.glob(os.path.join(DOWNLOAD_DIR, "*.xlsx"))
            new_files = [f for f in after if f not in before]
            if new_files:
                newest = max(new_files, key=os.path.getmtime)
                log.info(f"Downloaded errors Excel: {newest}")
                return newest
        except Exception as e:
            log.warning(f"Could not download errors: {e}")
        return None

    def _close_form(self, page):
        try:
            page.click_cancel_or_dismiss_dialog()
            page.wait_seconds(1)
        except Exception:
            pass

    def _run_field_test(self, driver, page, locator, field_name, bad_value, desc, category="Step 1"):
        """
        Test one field: type bad value, click Next, check for mat-error.
        Returns True if validation error was shown.
        """
        # Type bad value
        page.type_text(locator, bad_value, clear_first=True)
        page.wait_seconds(0.3)

        # Click Next (should be blocked by validation)
        try:
            page._click_next()
        except Exception:
            pass
        page.wait_seconds(1)

        # Check field state
        state = self._check_field_state(driver, field_name)
        showing = state.get("is_showing_error", False)
        err_text = state.get("error_text", "")

        shot = self._take_screenshot(driver, f"val_{field_name.replace(' ', '_').lower()}")

        self._record(
            test_name=f"{category}: {desc}",
            category=category,
            field=field_name,
            bad_value=repr(bad_value),
            expected="mat-error visible on Next click",
            actual=f"showing={showing}, error='{err_text}'",
            status="PASSED" if showing else "FAILED",
            screenshot=shot,
        )

        return showing

    # ================================================================
    # BUG DISCOVERY TESTS
    # ================================================================

    def test_01_header_untouched_bug(self, logged_in_driver):
        """
        BUG: Required header fields (Company Name, Entity Group, etc.)
        don't show validation errors when Next is clicked without
        touching them first.

        Angular marks them ng-invalid but NOT ng-touched,
        so mat-error elements remain hidden.
        """
        driver = logged_in_driver
        page = self._page(driver)

        self._open_fresh_form(page)

        # Click Next WITHOUT touching any header field
        try:
            page._click_next()
        except Exception:
            pass
        page.wait_seconds(1)

        shot = self._take_screenshot(driver, "BUG_01_header_untouched")

        header_fields = ["Company Name", "Company Short Name"]
        for field_name in header_fields:
            state = self._check_field_state(driver, field_name)
            is_bug = (
                state.get("is_invalid", False)
                and not state.get("is_touched", False)
                and not state.get("is_showing_error", False)
            )

            self._record(
                test_name=f"BUG: Untouched '{field_name}' should show error",
                category="Bug Discovery",
                field=field_name,
                bad_value="(empty, untouched)",
                expected="mat-error visible on Next click",
                actual=(
                    f"ng-invalid={state.get('is_invalid')}, "
                    f"touched={state.get('is_touched')}, "
                    f"showing_error={state.get('is_showing_error')}"
                ),
                status="FAILED" if is_bug else "PASSED",
                is_bug=is_bug,
                impact="User gets no feedback that required field is empty until clicking into it.",
                screenshot=shot,
            )

        self._close_form(page)

    def test_02_header_touched_should_error(self, logged_in_driver):
        """
        PROVE THE FIX: After clicking into a header field and leaving it empty,
        validation errors SHOULD appear on Next click.

        This proves the validation logic EXISTS but only fires for touched fields.
        """
        driver = logged_in_driver
        page = self._page(driver)

        self._open_fresh_form(page)

        # Click into Company Name, then blur
        try:
            inp = driver.find_element(By.CSS_SELECTOR, "input[name='Company Name']")
            inp.click()
            page.wait_seconds(0.3)
            driver.find_element(By.CSS_SELECTOR, "mat-dialog-container").click()
            page.wait_seconds(0.3)
        except Exception:
            pass

        # Click Next
        try:
            page._click_next()
        except Exception:
            pass
        page.wait_seconds(1)

        shot = self._take_screenshot(driver, "BUG_02_header_touched")

        state = self._check_field_state(driver, "Company Name")
        shows = state.get("is_showing_error", False)

        self._record(
            test_name="BUG: Touched empty field SHOULD show error (proves fix direction)",
            category="Bug Discovery",
            field="Company Name",
            bad_value="(empty, touched + blurred)",
            expected="mat-error visible after touch + Next",
            actual=f"touched={state.get('is_touched')}, showing={shows}",
            status="PASSED" if shows else "FAILED",
            is_bug=False,
            impact="Proves Angular validation works for touched fields. Untouched bug is confirmed.",
            screenshot=shot,
        )

        self._close_form(page)

    def test_03_max_length_bug(self, logged_in_driver):
        """
        BUG: Text fields accept >250 characters but submit fails
        silently with no field-level error or character limit indicator.
        """
        driver = logged_in_driver
        page = self._page(driver)

        self._open_fresh_form(page)

        long_name = "A" * 300
        page.type_text(page.COMPANY_NAME_INPUT, long_name, clear_first=True)
        page.wait_seconds(0.5)

        actual_value = page.get_text(page.COMPANY_NAME_INPUT) or ""
        actual_len = len(actual_value)
        over_limit = actual_len > 250

        shot = self._take_screenshot(driver, "BUG_03_max_length_300")

        self._record(
            test_name="BUG: Field accepts >250 chars without warning",
            category="Bug Discovery",
            field="Company Name",
            bad_value=f"(300 chars, accepted={actual_len})",
            expected="Should cap at 250 or show warning",
            actual=f"Accepted {actual_len} chars" if over_limit else f"Capped at {actual_len}",
            status="FAILED" if over_limit else "PASSED",
            is_bug=over_limit,
            impact="User types 300+ chars, form appears fine, submit fails with no explanation.",
            screenshot=shot,
        )

        # Also test textarea
        long_bg = "B" * 300
        page.type_text(page.COMPANY_BACKGROUND_INPUT, long_bg, clear_first=True)
        page.wait_seconds(0.5)
        bg_value = page.get_text(page.COMPANY_BACKGROUND_INPUT) or ""
        bg_len = len(bg_value)
        bg_bug = bg_len > 250

        shot2 = self._take_screenshot(driver, "BUG_03_max_length_textarea")

        self._record(
            test_name="BUG: Textarea accepts >250 chars without warning",
            category="Bug Discovery",
            field="Company Background",
            bad_value=f"(300 chars, accepted={bg_len})",
            expected="Should cap at 250 or show warning",
            actual=f"Accepted {bg_len} chars" if bg_bug else f"Capped at {bg_len}",
            status="FAILED" if bg_bug else "PASSED",
            is_bug=bg_bug,
            impact="Same bug on textarea. No maxlength attribute on the element.",
            screenshot=shot2,
        )

        self._close_form(page)
    # ================================================================
    # STEP 1: COMPANY DETAILS VALIDATION
    # ================================================================

    def test_04_step1_email_validations(self, logged_in_driver):
        """Test email field: empty, invalid format, no domain."""
        driver = logged_in_driver
        page = self._page(driver)

        self._open_fresh_form(page)
        self._fill_all_valid(page, self._unique_name())

        email_tests = [
            ("", "empty email"),
            ("notanemail", "no @ symbol"),
            ("test@", "no domain"),
            ("test @mail.com", "space in email"),
        ]

        for bad_val, desc in email_tests:
            page.type_text(page.EMAIL_INPUT, bad_val, clear_first=True)
            page.wait_seconds(0.3)
            try:
                page._click_next()
            except Exception:
                pass
            page.wait_seconds(1)

            state = self._check_field_state(driver, "Email ")
            showing = state.get("is_showing_error", False)

            shot = self._take_screenshot(
                driver, f"val_email_{desc.replace(' ', '_')}"
            )

            self._record(
                test_name=f"Step 1: {desc}",
                category="Step 1 - Email",
                field="Email",
                bad_value=repr(bad_val),
                expected="mat-error visible on Next click",
                actual=f"showing={showing}, error='{state.get('error_text', '')}'",
                status="PASSED" if showing else "FAILED",
                screenshot=shot,
            )

        self._close_form(page)

    def test_05_step1_mobile_validations(self, logged_in_driver):
        """Test mobile number: empty, letters, too short."""
        driver = logged_in_driver
        page = self._page(driver)

        self._open_fresh_form(page)
        self._fill_all_valid(page, self._unique_name())

        mobile_tests = [
            ("", "empty mobile"),
            ("abc123", "letters in mobile"),
            ("12345", "too short (5 digits)"),
        ]

        for bad_val, desc in mobile_tests:
            page.type_text(page.MOBILE_NUMBER_INPUT, bad_val, clear_first=True)
            page.wait_seconds(0.3)
            try:
                page._click_next()
            except Exception:
                pass
            page.wait_seconds(1)

            state = self._check_field_state(driver, "Mobile Number")
            showing = state.get("is_showing_error", False)

            shot = self._take_screenshot(
                driver, f"val_mobile_{desc.replace(' ', '_')}"
            )

            self._record(
                test_name=f"Step 1: {desc}",
                category="Step 1 - Mobile",
                field="Mobile Number",
                bad_value=repr(bad_val),
                expected="mat-error visible on Next click",
                actual=f"showing={showing}, error='{state.get('error_text', '')}'",
                status="PASSED" if showing else "FAILED",
                screenshot=shot,
            )

        self._close_form(page)

    def test_06_step1_pan_gstin_validations(self, logged_in_driver):
        """Test PAN and GSTIN: empty, wrong format."""
        driver = logged_in_driver
        page = self._page(driver)

        self._open_fresh_form(page)
        self._fill_all_valid(page, self._unique_name())

        pan_tests = [
            ("", "empty PAN"),
            ("ABCDE", "PAN too short"),
        ]

        for bad_val, desc in pan_tests:
            page.type_text(page.PAN_INPUT, bad_val, clear_first=True)
            page.wait_seconds(0.3)
            try:
                page._click_next()
            except Exception:
                pass
            page.wait_seconds(1)

            state = self._check_field_state(driver, "PAN")
            showing = state.get("is_showing_error", False)

            shot = self._take_screenshot(
                driver, f"val_pan_{desc.replace(' ', '_')}"
            )

            self._record(
                test_name=f"Step 1: {desc}",
                category="Step 1 - PAN",
                field="PAN",
                bad_value=repr(bad_val),
                expected="mat-error visible on Next click",
                actual=f"showing={showing}, error='{state.get('error_text', '')}'",
                status="PASSED" if showing else "FAILED",
                screenshot=shot,
            )

        # GSTIN tests
        gstin_tests = [
            ("", "empty GSTIN"),
            ("12345", "GSTIN too short"),
        ]

        for bad_val, desc in gstin_tests:
            page.type_text(page.GSTIN_INPUT, bad_val, clear_first=True)
            page.wait_seconds(0.3)
            try:
                page._click_next()
            except Exception:
                pass
            page.wait_seconds(1)

            state = self._check_field_state(driver, "GSTIN")
            showing = state.get("is_showing_error", False)

            shot = self._take_screenshot(
                driver, f"val_gstin_{desc.replace(' ', '_')}"
            )

            self._record(
                test_name=f"Step 1: {desc}",
                category="Step 1 - GSTIN",
                field="GSTIN",
                bad_value=repr(bad_val),
                expected="mat-error visible on Next click",
                actual=f"showing={showing}, error='{state.get('error_text', '')}'",
                status="PASSED" if showing else "FAILED",
                screenshot=shot,
            )

        self._close_form(page)

    # ================================================================
    # STEP 2: PROMOTERS VALIDATION
    # ================================================================

    def test_07_step2_empty_promoter(self, logged_in_driver):
        """Test: empty promoter name on Step 2."""
        driver = logged_in_driver
        page = self._page(driver)
        company = self._unique_name()

        self._navigate_to_step(page, 2, company)

        # Type empty promoter name
        name_loc = ("xpath", "(//app-dynamic-details//input[@name='Name'])[1]")
        page.type_text(name_loc, "", clear_first=True)
        page.wait_seconds(0.3)

        try:
            page._click_next()
        except Exception:
            pass
        page.wait_seconds(1)

        state = self._check_field_state(driver, "Name")
        showing = state.get("is_showing_error", False)

        shot = self._take_screenshot(driver, "val_step2_empty_promoter")

        self._record(
            test_name="Step 2: Empty promoter name",
            category="Step 2 - Promoters",
            field="Promoter Name",
            bad_value='""',
            expected="mat-error visible on Next click",
            actual=f"showing={showing}, error='{state.get('error_text', '')}'",
            status="PASSED" if showing else "FAILED",
            screenshot=shot,
        )

        self._close_form(page)

    # ================================================================
    # STEP 3: ADDRESS VALIDATION
    # ================================================================

    def test_08_step3_address_validations(self, logged_in_driver):
        """Test: PIN code with letters and too short."""
        driver = logged_in_driver
        page = self._page(driver)
        company = self._unique_name()

        self._navigate_to_step(page, 3, company)

        pin_loc = ("xpath", "(//app-dynamic-details//input[@name='Pin Code'])[1]")

        pin_tests = [
            ("abc123", "PIN with letters"),
            ("1234", "PIN too short (4 digits)"),
        ]

        for bad_val, desc in pin_tests:
            page.type_text(pin_loc, bad_val, clear_first=True)
            page.wait_seconds(0.3)
            try:
                page._click_next()
            except Exception:
                pass
            page.wait_seconds(1)

            state = self._check_field_state(driver, "Pin Code")
            showing = state.get("is_showing_error", False)

            shot = self._take_screenshot(
                driver, f"val_pin_{desc.replace(' ', '_')}"
            )

            self._record(
                test_name=f"Step 3: {desc}",
                category="Step 3 - Address",
                field="Pin Code",
                bad_value=repr(bad_val),
                expected="mat-error visible on Next click",
                actual=f"showing={showing}, error='{state.get('error_text', '')}'",
                status="PASSED" if showing else "FAILED",
                screenshot=shot,
            )

        self._close_form(page)

    # ================================================================
    # MAX LENGTH TESTS (known limits)
    # ================================================================

    def test_09_max_length_fields(self, logged_in_driver):
        """Test fields that have known varchar limits: type limit+1, fill rest, submit."""
        driver = logged_in_driver
        page = self._page(driver)

        # Each entry: (locator, field_name, display_name, limit, step_to_navigate)
        limit_tests = [
            (page.COMPANY_SHORT_NAME_INPUT, "Company Short Name", "Company Short Name", 255, 1),
        ]

        for loc, fname, display, limit, step in limit_tests:
            company = self._unique_name()
            self._navigate_to_step(page, step, company)

            over_val = "A" * (limit + 1)
            page.type_text(loc, over_val, clear_first=True)
            page.wait_seconds(0.3)

            shot = self._take_screenshot(
                driver, f"val_maxlen_{fname.replace(' ', '_')}"
            )

            actual = page.get_text(loc) or ""
            accepted = len(actual) > limit

            self._record(
                test_name=f"Max Length: {display} (limit={limit})",
                category="Max Length",
                field=display,
                bad_value=f"({limit+1} chars, accepted={len(actual)})",
                expected="Should cap at limit or warn",
                actual=f"Accepted {len(actual)} chars" if accepted else f"Blocked at {len(actual)}",
                status="FAILED" if accepted else "PASSED",
                is_bug=accepted,
                impact=f"User can type {len(actual)} chars but DB limit is {limit}. Submit will fail silently.",
                screenshot=shot,
            )

        self._close_form(page)
    # ================================================================
    # EDGE CASES
    # ================================================================

    def test_10_duplicate_company_name(self, logged_in_driver):
        """Test: using an existing company name should fail."""
        driver = logged_in_driver
        page = self._page(driver)

        self._open_fresh_form(page)

        # First create a company
        company = self._unique_name()
        page.type_text(page.COMPANY_NAME_INPUT, company, clear_first=True)
        page.wait_seconds(0.5)

        # Just type a duplicate of a likely existing name
        dup_name = "Test Company"
        page.type_text(page.COMPANY_NAME_INPUT, dup_name, clear_first=True)
        page.wait_seconds(0.5)

        shot = self._take_screenshot(driver, "val_duplicate_name")

        # We can't assert much here without knowing if the name exists
        # but we record it for the report
        self._record(
            test_name="Edge Case: Duplicate company name",
            category="Edge Cases",
            field="Company Name",
            bad_value=repr(dup_name),
            expected="Should warn that company already exists",
            actual="Test recorded — check if duplicate warning appears on submit",
            status="PASSED",
            screenshot=shot,
        )

        self._close_form(page)

    def test_11_xss_in_company_name(self, logged_in_driver):
        """Test: XSS script tag in Company Name field."""
        driver = logged_in_driver
        page = self._page(driver)

        self._open_fresh_form(page)

        xss_payload = "<script>alert('XSS')</script>"
        page.type_text(page.COMPANY_NAME_INPUT, xss_payload, clear_first=True)
        page.wait_seconds(0.5)

        # Check if the input still has the raw script tag (not sanitized on input)
        actual = page.get_text(page.COMPANY_NAME_INPUT) or ""
        raw_stored = xss_payload in actual

        shot = self._take_screenshot(driver, "val_xss_company_name")

        self._record(
            test_name="Edge Case: XSS script tag in Company Name",
            category="Edge Cases",
            field="Company Name",
            bad_value=repr(xss_payload),
            expected="Should sanitize or strip script tags",
            actual=f"Raw script stored={raw_stored}" if raw_stored else "Script tag sanitized",
            status="FAILED" if raw_stored else "PASSED",
            is_bug=raw_stored,
            impact="XSS payload stored raw. Could execute when displayed on other pages.",
            screenshot=shot,
        )

        self._close_form(page)

    def test_12_special_chars_in_name(self, logged_in_driver):
        """Test: special characters in Company Name."""
        driver = logged_in_driver
        page = self._page(driver)

        self._open_fresh_form(page)

        special = "Test@#$%^&*()! Company"
        page.type_text(page.COMPANY_NAME_INPUT, special, clear_first=True)
        page.wait_seconds(0.5)

        actual = page.get_text(page.COMPANY_NAME_INPUT) or ""
        accepted = special == actual

        shot = self._take_screenshot(driver, "val_special_chars")

        self._record(
            test_name="Edge Case: Special characters in Company Name",
            category="Edge Cases",
            field="Company Name",
            bad_value=repr(special),
            expected="Should either accept or show clear rejection",
            actual=f"Accepted as-is={accepted}, value='{actual}'",
            status="PASSED",
            screenshot=shot,
        )

        self._close_form(page)

    # ================================================================
    # SWEETALERT + DOWNLOAD ERRORS
    # ================================================================

    def test_13_sweetalert_validation_popup(self, logged_in_driver):
        """
        Test: Trigger Validation Failed SweetAlert and download errors Excel.
        Fill all steps with valid data but leave Step 5 empty to trigger popup on submit.
        """
        driver = logged_in_driver
        page = self._page(driver)
        company = self._unique_name()

        # Navigate through all steps to reach submit
        self._navigate_to_step(page, 5, company)

        # Now on Step 5 (Infrastructure) — leave it empty
        # Try to submit anyway
        try:
            page._click_next()
            page.wait_seconds(1)
        except Exception:
            pass

        popup = self._check_sweetalert(driver, timeout=8)

        shot = self._take_screenshot(driver, "val_sweetalert_popup")

        if popup["appeared"]:
            self._record(
                test_name="SweetAlert: Validation Failed popup appeared",
                category="SweetAlert",
                field="N/A",
                bad_value="(empty Step 5)",
                expected="Validation Failed popup with Download Errors button",
                actual=f"Title='{popup['title']}', Message='{popup['message']}', DownloadBtn={popup['has_download_button']}",
                status="PASSED",
                screenshot=shot,
            )

            # Try to download errors Excel
            downloaded = self._download_validation_errors(driver)

            if downloaded:
                self._record(
                    test_name="SweetAlert: Downloaded errors Excel",
                    category="SweetAlert",
                    field="N/A",
                    bad_value="N/A",
                    expected="Excel file downloaded successfully",
                    actual=f"Saved to: {downloaded}",
                    status="PASSED",
                    screenshot=shot,
                )
            else:
                self._record(
                    test_name="SweetAlert: Download errors Excel",
                    category="SweetAlert",
                    field="N/A",
                    bad_value="N/A",
                    expected="Excel file downloaded",
                    actual="Download failed or file not found",
                    status="FAILED",
                    screenshot=shot,
                )

            # Dismiss popup
            self._dismiss_sweetalert(driver)
        else:
            self._record(
                test_name="SweetAlert: Validation Failed popup",
                category="SweetAlert",
                field="N/A",
                bad_value="(empty Step 5)",
                expected="Validation Failed popup",
                actual="No popup appeared",
                status="FAILED",
                screenshot=shot,
            )

        self._close_form(page)

    # ================================================================
    # MAX LENGTH - DEEPER FIELDS
    # ================================================================

    def test_14_max_length_business_fields(self, logged_in_driver):
        """Test Business Model (100 limit) exceeds."""
        driver = logged_in_driver
        page = self._page(driver)
        company = self._unique_name()

        self._navigate_to_step(page, 4, company)

        # Business Model has 100 limit
        biz_loc = ("xpath", "(//app-dynamic-details//mat-label[normalize-space(.)='Business Model']/ancestor::mat-form-field//input)[1]")
        over_val = "A" * 101
        page.type_text(biz_loc, over_val, clear_first=True)
        page.wait_seconds(0.5)

        shot = self._take_screenshot(driver, "val_maxlen_business_model")

        try:
            actual = page.get_text(biz_loc) or ""
            accepted = len(actual) > 100
        except Exception:
            actual = ""
            accepted = False

        self._record(
            test_name="Max Length: Business Model (limit=100)",
            category="Max Length",
            field="Business Model",
            bad_value=f"(101 chars, accepted={len(actual)})",
            expected="Should cap at 100 or warn",
            actual=f"Accepted {len(actual)} chars" if accepted else f"Blocked at {len(actual)}",
            status="FAILED" if accepted else "PASSED",
            is_bug=accepted,
            impact=f"DB limit is 100 but input accepted {len(actual)} chars.",
            screenshot=shot,
        )

        self._close_form(page)

    def test_15_max_length_promoter_name(self, logged_in_driver):
        """Test Promoter Name (100 limit) exceeds."""
        driver = logged_in_driver
        page = self._page(driver)
        company = self._unique_name()

        self._navigate_to_step(page, 2, company)

        name_loc = ("xpath", "(//app-dynamic-details//input[@name='Name'])[1]")
        over_val = "A" * 101
        page.type_text(name_loc, over_val, clear_first=True)
        page.wait_seconds(0.5)

        shot = self._take_screenshot(driver, "val_maxlen_promoter_name")

        try:
            actual = page.get_text(name_loc) or ""
            accepted = len(actual) > 100
        except Exception:
            actual = ""
            accepted = False

        self._record(
            test_name="Max Length: Promoter Name (limit=100)",
            category="Max Length",
            field="Promoter Name",
            bad_value=f"(101 chars, accepted={len(actual)})",
            expected="Should cap at 100 or warn",
            actual=f"Accepted {len(actual)} chars" if accepted else f"Blocked at {len(actual)}",
            status="FAILED" if accepted else "PASSED",
            is_bug=accepted,
            impact=f"DB limit is 100 but input accepted {len(actual)} chars.",
            screenshot=shot,
        )

        self._close_form(page)

    def test_16_max_length_infra_location(self, logged_in_driver):
        """Test Infrastructure Location (50 limit) exceeds."""
        driver = logged_in_driver
        page = self._page(driver)
        company = self._unique_name()

        self._navigate_to_step(page, 5, company)

        over_val = "A" * 51
        page.type_text(page.INFRA_LOCATION_INPUT, over_val, clear_first=True)
        page.wait_seconds(0.5)

        shot = self._take_screenshot(driver, "val_maxlen_infra_location")

        try:
            actual = page.get_text(page.INFRA_LOCATION_INPUT) or ""
            accepted = len(actual) > 50
        except Exception:
            actual = ""
            accepted = False

        self._record(
            test_name="Max Length: Infrastructure Location (limit=50)",
            category="Max Length",
            field="Infrastructure Location",
            bad_value=f"(51 chars, accepted={len(actual)})",
            expected="Should cap at 50 or warn",
            actual=f"Accepted {len(actual)} chars" if accepted else f"Blocked at {len(actual)}",
            status="FAILED" if accepted else "PASSED",
            is_bug=accepted,
            impact=f"DB limit is 50 but input accepted {len(actual)} chars.",
            screenshot=shot,
        )

        self._close_form(page)


# ================================================================
# PYTEST HOOK — Generate Validation Report
# ================================================================

def pytest_sessionfinish(session, exitstatus):
    """Generate validation Excel report after all tests complete."""
    from pages.company_onboarding.test.validation_results_store import validation_results
    from pages.company_onboarding.test.validation_report_generator import generate_validation_report

    if not validation_results:
        return

    try:
        filepath = generate_validation_report(validation_results, REPORT_DIR)
        total = len(validation_results)
        passed = sum(1 for r in validation_results if r["status"] == "PASSED")
        failed = sum(1 for r in validation_results if r["status"] == "FAILED")
        bugs = sum(1 for r in validation_results if r.get("is_bug"))

        log.separator()
        log.info(" COMPANY ONBOARDING VALIDATION REPORT")
        log.info(f" Total: {total} | Passed: {passed} | Failed: {failed} | Bugs Found: {bugs}")
        log.info(f" Report: {filepath}")
        log.separator()

        validation_results.clear()
    except Exception as e:
        log.error(f"Failed to generate validation report: {e}")